### ISSUE TITLE
Access token as authentication method possible?

### ISSUE THREAD

**Issue by tfranssen** [victronenergy/dbus-flashmq#5]
Hi, 

Is it possible to use a access token instead of the username and password to connect with the VRM MQTT broker? 

Thanks!

**Comment by wiebeytec** [comment]
Yes, actually, but it's undocumented at this point. Just use your VRM e-mail as username and `Token <token>` as password.

This should be made the recommended way, and probably will be.

**Comment by tfranssen** [comment]
That is great! Thanks for the fast reply.

**Comment by wiebeytec** [comment]
Documentation has been updated.
